######################################################
#                   TV Collections                   #
######################################################

templates:
  collection:
    optional:
      - show
      - tvdb
      - tvdbshow
      - trakt
      - imdb
      - sort
    tmdb_show: <<show>>
    tvdb_show: <<tvdbshow>>
    tvdb_list_details: https://thetvdb.com/lists/<<tvdb>>
    trakt_list_details: https://trakt.tv/users/<<trakt>>
    imdb_id: <<imdb>>
    sort_title: <<sort>>

collections:
  Adventure Time:
    template: {name: collection, show: "15260, 131378", imdb: tt11165358}
    summary: Adventure Time is an American animated fantasy franchise created by Pendleton Ward, set in the post-apocalyptic Land of Ooo.
  American Story:
    template: {name: collection, tvdb: 8411}
    summary: American Story is an American anthology media franchise consisting of several television series. Each series follows a different genre of fiction, with each individual season conceived as a self-contained miniseries, following a different set of characters and settings, and a story line with its own "'beginning, middle, and end.'" Many actors appear in more than one season and series, often playing a new character.
  "Avatar: The Last Airbender":
    template: {name: collection, tvdb: 8116} 
  Band of Brothers:
    template: {name: collection, tvdb: band-of-brothers}
  The Big Bang Theory:
    template: {name: collection, tvdb: the-big-bang-theory, sort: Big Bang Theory}
  The Blacklist:
    template: {name: collection, tvdb: the-blacklist, sort: Blacklist}
  Bosch:
    template: {name: collection, tvdb: bosch}
    summary: "Based on Michael Connelly's best-selling novels, these are the stories of relentless LAPD homicide Detective Harry Bosch who pursues justice at all costs. But behind his tireless momentum is a man who is haunted by his past and struggles to remain loyal to his personal code: 'Everybody counts or nobody counts.'"
  The Boys:
    template: {name: collection, tvdb: the-boys}
    summary: The Boys is an American media franchise based on the comic book series of the same name. Consisting of action-drama/satirical black comedy superhero streaming television series which follow the residents of a world where superpowered individuals called Supes are recognized as heroes by the general public and work for a powerful corporation known as Vought International, which markets, monetizes, and (secretly) creates them, with most being selfish and corrupt outside of their heroic personas.
  Breaking Bad:
    template: {name: collection, tvdb: breaking-bad, show: 90746}
    summary: "Breaking Bad revolves around a terminally ill chemistry teacher, Walter White, who teams up with a former student, Jesse Pinkman, to manufacture crystal meth to secure his family's future. El Camino and Better Call Saul cover events that take place before and after the main show respectively."
  Buffyverse:
    template: {name: collection, tvdb: buffyverse}
    summary: The Buffyverse, a term, originally coined by fans, refers to the shared fictional universe in which the television series Buffy the Vampire Slayer and Angel are set.
  Clifford the Big Red Dog:
    template: {name: collection, tvdb: 8749}
  DC Animated Universe:
    template: {name: collection, tvdb: dc-animated-universe}
    summary: The DC Animated Universe (DCAU, also referred to as the Timmverse or Diniverse by fans) is a shared universe centered on a group of animated television series based on DC Comics and produced by Warner Bros. Animation.
  Dexter:
    template: {name: collection, tvdb: dexter}
    summary: "Dexter is an American crime drama television series. Set in Miami, the series centers on Dexter Morgan, a forensic technician specializing in bloodstain pattern analysis for the fictional Miami Metro Police Department, who leads a secret parallel life as a vigilante serial killer, hunting down murderers who have not been adequately punished by the justice system due to corruption or legal technicalities. Eight years after the series finale Dexter returned in the limited series Dexter: New Blood."
  Doctor Who:
    template: {name: collection, tvdb: doctor-who}
    summary: Doctor Who is a British science-fiction television programme broadcast by the BBC since 1963. The programme depicts the adventures of a Time Lord called the Doctor, an extraterrestrial being who appears to be human. The Doctor explores the universe in a time-travelling space ship called the TARDIS, which appears as a blue British police box.
  Frasier:
    template: {name: collection, show: "3452, 195241"}
    summary: After many years spent at the “Cheers” bar, Frasier moves back home to Seattle to work as a radio psychiatrist after his policeman father gets shot in the hip on duty. Years later, Frasier starts the next chapter of his life as he returns to Boston, Mass., with new challenges to face, new relationships to forge and an old dream or two to finally fulfill.
  Full House:
    template: {name: collection, tvdb: full-house}
    summary: Full House is an American television sitcom about widowed father Danny Tanner who enlists his brother-in-law Jesse Katsopolis and childhood best friend Joey Gladstone to help raise his three daughters, eldest D.J., middle child Stephanie and youngest Michelle in his San Francisco home. A sequel series, Fuller House, aired 11 years later and follows the adult lives of D.J. amd Stephanie.
  Game of Thrones:
    template: {name: collection, tvdb: game-of-thrones}
  Gilmore Girls:
    template: {name: collection, tvdb: gilmore-girls}
    summary: "Gilmore Girls is an American comedy-drama television series which has been voted one of the 100 greatest television shows of all time in Time magazine. A four-part miniseries revival Gilmore Girls: A Year in the Life aired 9 years after the origianl series finale."
  Harley Quinn:
    template: {name: collection, tvdb: harley-quinn}
    summary: "Harley Quinn is an American adult animated dark comedy superhero television series based on the DC Comics character of the same name. It follows the misadventures of Harley Quinn and her best friend (and eventual lover), Poison Ivy, after leaving her boyfriend, the Joker. Noonan's, is a spin-off featuring Kite Man and his current girlfriend Golden Glider."
  How I Met Your...:
    template: {name: collection, tvdb: how-i-met-your-mother}
    summary: How I Met Your Mother/Father are a collection of sitcoms narated by an older version of the main character as they tell their children how they met their mother/father.
  Justified:
    template: {name: collection, tvdb: justified}
    summary: "Justified is an American Western crime drama television series based on novels by Elmore Leonard. Justified: City Primeval, is a limited sequel series."
  Long Way:
    template: {name: collection, tvdb: long-way}
  Looney Tunes:
    template: {name: collection, tvdbshow: 72514, show: "65763, 102321"}
    summary: Looney Tunes is an American animated franchise produced and distributed by Warner Bros. It began as a series of short films that originally ran from 1930 to 1969, during the golden age of American animation.
  Pretty Little Liars:
    template: {name: collection, tvdb: pretty-little-liars}
  Stargate:
    template: {name: collection, tvdb: stargate}
  Star Trek:
    template: {name: collection, tvdb: star-trek}
    summary: Space... the final frontier. Star Trek is an American science fiction media franchise created by Gene Roddenberry, which began with the eponymous 1960s television series. 
  Star Wars:
    template: {name: collection, tvdb: star-wars}
    summary: "An epic space-opera series, which depicts the adventures of various characters 'a long time ago in a galaxy far, far away….'"
  Supernatural:
    template: {name: collection, tvdb: supernatural}
    summary: "Supernatural is an American dark fantasy drama television series which follows the two Winchester brothers, Sam and Dean, as they hunt demons, ghosts, monsters, and other supernatural beings. A spin-off, The Winchesters, will explore how Sam amd Dean's parents met." 
  The Vampire Diaries:
    template: {name: collection, tvdb: the-vampire-diaries, sort: Vampire Diaries}
  Walker:
    template: {name: collection, tvdb: walker}
    summary: Walker is an American action crime drama television series, it is a reboot of the 1990’s western drama television series Walker, Texas Ranger.  
  The Walking Dead:
    template: {name: collection, tvdb: the-walking-dead, show: "129035, 211684", sort: Walking Dead}
    summary: Fight the dead. Fear the living. The Walking Dead is a zombie apocalypse media franchise based on the comic book series of the same name, created by writer Robert Kirkman and artist Tony Moore.
  The Witcher:
    template: {name: collection, tvdb: the-witcher, sort: Witcher}
  X-Men:
    template: {name: collection, tvdb: x-men-animated-series}
    summary: "X-Men: The Animated Series, is an animated superhero television series that aired for five seasons from October 31, 1992, to September 20, 1997. Set in the same fictional universe as Spider-Man, Earth-92131, it was followed by a revival, X-Men '97, which began airing on March 20, 2024."
  Yellowstone:
    template: {name: collection, tvdb: yellowstone}
    title.not: "Lawmen: Bass Reeves"
    summary: "Yellowstone is an American neo-Western drama television series and follows the Dutton family, owners of the largest ranch in Montana, the Yellowstone Dutton Ranch, commonly called 'the Yellowstone'. Various spin-offs explore different generations of the Dutton family across differemt time periods."
