######################################################
#                Studio Collections                  #
######################################################

templates:
  studio:
    smart_label:
      sort_by: release.asc
      all:
        label: <<smart_label>>
    optional:
      - movie
      - trakt
      - radarr
    tmdb_movie: <<movie>>
    trakt_list: https://trakt.tv/users/<<trakt>>
    radarr_add_missing: <<radarr>>
    sort_title: +<<collection_name>>

collections:
  A24:
    template: {name: studio, trakt: fidel-cb/lists/a24}
    summary: A24 is an American independent entertainment company that specializes in film and television production, as well as film distribution.
  Disney Animation Studios:
    template: {name: studio, trakt: jashack/lists/walt-disney-animation-studios, radarr: true}
    summary: Walt Disney Animation Studios, sometimes shortened to Disney Animation, is an American animation studio that creates animated features and short films for The Walt Disney Company. Founded on October 16, 1923, it is one of the oldest-running animation studios in the world. It is currently organized as a division of Walt Disney Studios and is headquartered at the Walt Disney Studios lot in Burbank, California.
  Disney Animation Studios Shorts:
    template: {name: studio, trakt: dagov765/lists/walt-disney-animation-studios-shorts, radarr: true}
    summary:
  Disney Live-Action Remakes:
    template: {name: studio, trakt: proturbo18/lists/disney-live-action-remakes, radarr: true}
    summary: Walt Disney Pictures is an American film production studio of The Walt Disney Studios, which is owned by The Walt Disney Company. The studio is the flagship producer of live-action feature films within the Walt Disney Studios unit, and is based at the Walt Disney Studios in Burbank, California. Walt Disney Studios Motion Pictures distributes and markets the films produced by Walt Disney Pictures.
  Pixar:
    template: {name: studio, trakt: chloe131997/lists/pixar, radarr: true}
    summary: Pixar Animation Studios, commonly known as Pixar, is an American computer animation studio based in Emeryville, California, a subsidiary of Disney Studios owned by The Walt Disney Company. Pixar began in 1979 and was purchased by Disney in 2006 at a valuation of $7.4 billion. Pixar is best known for its feature films and animated shorts. Luxo Jr., a desk lamp from the studio's 1986 short film of the same name, is the studio's mascot.
  Pixar Shorts:
    template: {name: studio, trakt: avaianade/lists/pixar-shorts, radarr: true}
    summary:
  Studio Ghibli:
    template: {name: studio, trakt: asterlea/lists/studio-ghibli, movie: 1044343, radarr: true}
    summary: Studio Ghibli Inc. is a Japanese animation film studio headquartered in Koganei, Tokyo. The studio is best known for its animated feature films, and has also produced several short films, television commercials, and one television film. The studio’s mascot and most recognizable symbol is the character, Totoro, a giant cat-like spirit from the 1988 classic, My Neighbor Totoro.
