######################################################
#                Studio Collections                  #
######################################################

templates:
  studio:
    smart_label:
      sort_by: release.asc
      all:
        label: <<smart_label>>
    optional:
      - movie
      - trakt
      - radarr
    tmdb_movie: <<movie>>
    trakt_list: https://trakt.tv/users/<<trakt>>
    radarr_add_missing: <<radarr>>
    sort_title: +<<collection_name>>

collections:
  Studio Ghibli:
    template: {name: studio, trakt: asterlea/lists/studio-ghibli, radarr: true}
    summary: Studio Ghibli Inc. is a Japanese animation film studio headquartered in Koganei, Tokyo. The studio is best known for its animated feature films, and has also produced several short films, television commercials, and one television film. The studio’s mascot and most recognizable symbol is the character, Totoro, a giant cat-like spirit from the 1988 classic, My Neighbor Totoro.
