######################################################
#                  Chart Collections                 #
######################################################

templates:
  unwatched:
    conditionals:
      episodes:
        default: ""
        conditions:
          - library_type: show
            value: "_episodes"
      description:
        default: ""
        conditions:
          - library_type: show
            value: " or have unplayed episodes"
    collection_filtering: user
    smart_filter:
      all:
        unplayed<<episodes>>: true
      sort_by: release.desc
    summary: "Collection of <<library_type>>s that haven't been watched<<description>>."
    sort_title: ++++++<<collection_name>>
  imdb:
    imdb_chart: <<chart>>_<<library_type>>s
    smart_label:
      sort_by: audience_rating.desc
      all:
        label: <<smart_label>>
    sort_title: +++++<<collection_name>>
    summary: The top 250 best <<library_type>>s of all time based on IMDb user ratings.
  charts:
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
    sort_title: +++++<<collection_name>>
    summary: Collection of <<library_type>>s trending this week on <<website>>, updated every Monday.
    schedule: weekly(monday)

collections:
  Unwatched:
    template: {name: unwatched, library_type: <<library_type>>}
  IMDb Top 250:
    template: {name: imdb, chart: top}
  TMDb Trending:
    template: {name: charts, website: TMDb}
    tmdb_trending_weekly: 100
  Trakt Trending:
    template: {name: charts, website: Trakt}
    trakt_chart:
      chart: trending
      limit: 100
